name: SEND EMAIL

on:
  workflow_dispatch:

jobs: 
  Email:
    runs-on: ubuntu-latest

    steps:
      - name: Install mailutils
        run: |
         sudo apt-get install -y mailutils
         
      - name: send email
        run: |
         echo "Test mail from GitHub with action details" >> email.txt
         cat email.txt | mailx -s "Test mail from GitHub" -S smtp=smtp.live.com:587 -S smptp-use-starttls -S smtp-auth=login -S smtp-auth-user="${{secrets.MAIL_USERNAME}}" -S smtp-auth-password="${{secrets.MAIL_PASSWORD}}" -S from="athulya.s01@infosys.com" shiyamsundar.k@infosys.com
        
        
         
#       - name: Send mail
#         uses: dawidd6/action-send-mail@v3
#         with:

#           server_address: smtp.office365.com
#           server_port: 587
#           # Optional whether this connection use TLS (default is true if server_port is 465)
#           username: ${{secrets.MAIL_USERNAME}}
#           password: ${{secrets.MAIL_PASSWORD}}        
#           subject: Test email
#           to: shiyamsundar.k@infosys.com
#           # Required sender full name (address can be skipped):
#           from: athulya.s01@infosys.com
#           body: Testing email sending action
#           priority: low
